// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/mpppk/imagine/action"
	"github.com/mpppk/imagine/domain/repository"
	"github.com/mpppk/imagine/infra"
	"github.com/mpppk/imagine/infra/repoimpl"
	"github.com/mpppk/imagine/usecase/interactor"
	"go.etcd.io/bbolt"
)

// Injectors from wire.go:

func NewBoltHandlerCreator(b *bbolt.DB) *action.HandlerCreator {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	usecaseAsset := interactor.NewAsset(asset, tag)
	usecaseTag := interactor.NewTag(tag)
	workSpace := repoimpl.NewBBoltWorkSpace(b)
	meta := repoimpl.NewBoltMeta(b)
	client := repository.NewClient(asset, tag, workSpace, meta)
	handlerCreator := action.NewHandlerCreator(usecaseAsset, usecaseTag, client, b)
	return handlerCreator
}

func InitializeAssetUseCase(b *bbolt.DB) *interactor.Asset {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	usecaseAsset := interactor.NewAsset(asset, tag)
	return usecaseAsset
}

func InitializeTagUseCase(b *bbolt.DB) *interactor.Tag {
	tag := repoimpl.NewBBoltTag(b)
	usecaseTag := interactor.NewTag(tag)
	return usecaseTag
}

func NewBoltClient(b *bbolt.DB) *repository.Client {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	workSpace := repoimpl.NewBBoltWorkSpace(b)
	meta := repoimpl.NewBoltMeta(b)
	client := repository.NewClient(asset, tag, workSpace, meta)
	return client
}

func NewBoltUseCases(b *bbolt.DB) *interactor.UseCases {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	workSpace := repoimpl.NewBBoltWorkSpace(b)
	meta := repoimpl.NewBoltMeta(b)
	useCases := interactor.New(asset, tag, workSpace, meta)
	return useCases
}

func NewBoltUseCasesWithDBPath(dbPath string) (*interactor.UseCases, error) {
	db, err := infra.NewBoltDB(dbPath)
	if err != nil {
		return nil, err
	}
	asset := repoimpl.NewBBoltAsset(db)
	tag := repoimpl.NewBBoltTag(db)
	workSpace := repoimpl.NewBBoltWorkSpace(db)
	meta := repoimpl.NewBoltMeta(db)
	useCases := interactor.New(asset, tag, workSpace, meta)
	return useCases, nil
}
