// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/mpppk/imagine/action"
	"github.com/mpppk/imagine/domain/client"
	"github.com/mpppk/imagine/infra"
	"github.com/mpppk/imagine/infra/queryimpl"
	"github.com/mpppk/imagine/infra/repoimpl"
	"github.com/mpppk/imagine/usecase/interactor"
	"go.etcd.io/bbolt"
)

// Injectors from wire.go:

func NewBoltHandlerCreator(b *bbolt.DB) *action.HandlerCreator {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	queryTag := queryimpl.NewBBoltTag(b)
	clientTag := client.NewTag(tag, queryTag)
	interactorAsset := interactor.NewAsset(asset, clientTag)
	interactorTag := interactor.NewTag(clientTag)
	workSpace := repoimpl.NewBBoltWorkSpace(b)
	meta := repoimpl.NewBoltMeta(b)
	clientClient := client.New(asset, clientTag, workSpace, meta)
	handlerCreator := action.NewHandlerCreator(interactorAsset, interactorTag, clientClient, b)
	return handlerCreator
}

func InitializeAssetUseCase(b *bbolt.DB) *interactor.Asset {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	queryTag := queryimpl.NewBBoltTag(b)
	clientTag := client.NewTag(tag, queryTag)
	interactorAsset := interactor.NewAsset(asset, clientTag)
	return interactorAsset
}

func InitializeTagUseCase(b *bbolt.DB) *interactor.Tag {
	tag := repoimpl.NewBBoltTag(b)
	queryTag := queryimpl.NewBBoltTag(b)
	clientTag := client.NewTag(tag, queryTag)
	interactorTag := interactor.NewTag(clientTag)
	return interactorTag
}

func NewBoltClient(b *bbolt.DB) *client.Client {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	queryTag := queryimpl.NewBBoltTag(b)
	clientTag := client.NewTag(tag, queryTag)
	workSpace := repoimpl.NewBBoltWorkSpace(b)
	meta := repoimpl.NewBoltMeta(b)
	clientClient := client.New(asset, clientTag, workSpace, meta)
	return clientClient
}

func NewBoltUseCases(b *bbolt.DB) *interactor.UseCases {
	asset := repoimpl.NewBBoltAsset(b)
	tag := repoimpl.NewBBoltTag(b)
	queryTag := queryimpl.NewBBoltTag(b)
	clientTag := client.NewTag(tag, queryTag)
	workSpace := repoimpl.NewBBoltWorkSpace(b)
	meta := repoimpl.NewBoltMeta(b)
	useCases := interactor.New(asset, clientTag, workSpace, meta)
	return useCases
}

func NewBoltUseCasesWithDBPath(dbPath string) (*interactor.UseCases, error) {
	db, err := infra.NewBoltDB(dbPath)
	if err != nil {
		return nil, err
	}
	asset := repoimpl.NewBBoltAsset(db)
	tag := repoimpl.NewBBoltTag(db)
	queryTag := queryimpl.NewBBoltTag(db)
	clientTag := client.NewTag(tag, queryTag)
	workSpace := repoimpl.NewBBoltWorkSpace(db)
	meta := repoimpl.NewBoltMeta(db)
	useCases := interactor.New(asset, clientTag, workSpace, meta)
	return useCases, nil
}
